---
name: Expo GitHub Action
author: Cedric van Putten <me@bycedric.com>
description: Use Expo CLI in your GitHub Actions workflow.
input:
  expo-version:
    description: The Expo CLI version to install, use any semver available.
    default: latest
  expo-manager:
    description: The package manger used to install the Expo CLI.
    default: npm
  expo-username:
    description: Your Expo username, for authentication.
  expo-password:
    description: Your Expo password, for authentication. (use with secrets)
branding:
  icon: terminal
  color: gray-dark
runs:
  using: node12
  main: build/index.js
